# Generated by Django 6.0.3 on 2026-05-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_dailyrecord_user_alter_dailyrecord_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyRecord',
        ),
    ]
