# Generated by Django 6.0.3 on 2026-05-15 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Волонтер'), ('seeker', 'Шукаю допомогу')], default='seeker', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Avatar',
            field=models.ImageField(default='default.png', upload_to='avatars/'),
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Відкрито'), ('closed', 'Закритий'), ('completed', 'Виповнений')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_taken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
