# Generated by Django 6.0.3 on 2026-05-15 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userprofile_role_alter_userprofile_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helprequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запит на допомогу', 'verbose_name_plural': 'Запити на допомогу'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профіль користувача', 'verbose_name_plural': 'Профілі користувачів'},
        ),
        migrations.AddField(
            model_name='helprequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата прийняття волонтером'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Контактний телефон'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='help_requests/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Місцезнаходження'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='urgency',
            field=models.CharField(choices=[('low', 'Низька'), ('medium', 'Середня'), ('high', 'Висока'), ('critical', 'Критична')], default='medium', max_length=20, verbose_name='Терміновість'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name="Ім'я"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(default=' ', max_length=100, verbose_name='Прізвище'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='description',
            field=models.TextField(verbose_name='Опис ситуації'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Автор запиту'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('open', 'Відкрито'), ('in_progress', 'У процесі'), ('closed', 'Закритий'), ('completed', 'Виповнений')], default='open', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_taken', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Avatar',
            field=models.ImageField(default='default.png', upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='Тут поки що нічого немає', max_length=500, verbose_name='Про себе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Волонтер'), ('seeker', 'Шукаю допомогу')], default='seeker', max_length=20, verbose_name='Роль'),
        ),
    ]
